### ISSUE TITLE
Config not saving

### ISSUE THREAD

**Issue by bjunited** [ProfiiQus/Mentionsgg#3] opened 2018-06-17 21:27 UTC
When I restart the server the config file does not save:

This is the config I tried to use, I am on Spigot 1.12.2 and latest version of the plugin.

General:
  Tags:
    Enabled: false
    Character: '@'
    Everyone: everyone
  Prefix: '&e[&bMentions&e]'
ChatNotification:
  Message: '%prefix% &6%sender% &ehas mentioned you in chat!'
TitleNotification:
  TitleMessage: '&eYou''ve been mentioned!'
  SubtitleMessage: '&e%sender% &9&l>> &6&o%message%'
SoundNotification:
  Sound: !!org.bukkit.Sound 'ENTITY_EXPERIENCE_ORB_PICKUP'
PermissedMentions:
- help
- officer
- manager
- master
- staff

Thank You
- bjunited

**Comment by ProfiiQus** [comment] 2018-06-21 20:33
Duplicate of [this bug](https://github.com/ProfiiQus/Mentionsgg/issues/2).
Follow the steps and everything will work smoothly once again :)

**Closed** 2018-06-24 19:14 UTC
